executable            = /afs/cern.ch/user/t/tvanlaer/Hc/higgscharm/condor/WWtoMuEle/2022postEE/DYto2L_2Jets_10to50_20/WWtoMuEle_DYto2L_2Jets_10to50_20.sh
arguments             = $(ClusterId)$(ProcId)
output                = /afs/cern.ch/user/t/tvanlaer/Hc/higgscharm/condor/logs/WWtoMuEle/2022postEE/DYto2L_2Jets_10to50_20/WWtoMuEle_DYto2L_2Jets_10to50_20.$(ClusterId).$(ProcId).out
error                 = /afs/cern.ch/user/t/tvanlaer/Hc/higgscharm/condor/logs/WWtoMuEle/2022postEE/DYto2L_2Jets_10to50_20/WWtoMuEle_DYto2L_2Jets_10to50_20.$(ClusterId).$(ProcId).err
log                   = /afs/cern.ch/user/t/tvanlaer/Hc/higgscharm/condor/logs/WWtoMuEle/2022postEE/DYto2L_2Jets_10to50_20/WWtoMuEle_DYto2L_2Jets_10to50_20.$(ClusterId).$(ProcId).log

+JobFlavour           = "longlunch"
+SingularityImage     = "/cvmfs/unpacked.cern.ch/registry.hub.docker.com/coffeateam/coffea-dask:latest-py3.9"
queue 1