goldenjson: analysis/data/Cert_Collisions2022_355100_362760_Golden.txt
lumidata: analysis/data/lumi2022.csv
hlt_paths:
  Muon:
    - SingleMu
  MuonEG:
    - MuEle
  EGamma:
    - SingleEle
object_selection:
  muons:
    field: events.Muon
    cuts:
      pt: events.Muon.pt > 5
      abseta: np.abs(events.Muon.eta) < 2.4
      dxy: events.Muon.dxy < 0.5
      dz: events.Muon.dz < 1
      sip3d: events.Muon.sip3d < 4
      reco: events.Muon.isGlobal | events.Muon.isTracker
      reliso: events.Muon.pfRelIso03_all < 0.35
      pt_id: ((events.Muon.pt < 200) & events.Muon.tightId) | ((events.Muon.pt >= 200) & ((events.Muon.tightId) | (events.Muon.highPtId == 1)))
  electrons:
    field: events.Electron
    cuts:
      pt: events.Electron.pt > 7
      abseta: np.abs(events.Electron.eta) < 2.5
      dxy: events.Electron.dxy < 0.5
      sip3d: events.Electron.sip3d < 4
      electron_id: wp80iso
      electron_muon_dr: delta_r_higher(events.Electron, objects['muons'], 0.4)
  leptons:
    field: select_hww_leptons
    cuts: null
  ll_pairs:
    field: select_hww_pairs
    cuts: 
      opposite_charge: (objects['ll_pairs'].l1.charge + objects['ll_pairs'].l2.charge == 0)
      mass_range: ((objects['ll_pairs'].l1 + objects['ll_pairs'].l2).mass > 12)
  cjets:
    field: events.Jet
    cuts:
      min_pt: events.Jet.pt > 20
      abseta: np.abs(events.Jet.eta) < 2.5
      jet_id: tightlepveto
      jet_particlenet_c: medium
      jet_lepton_dr: delta_r_higher(events.Jet, objects['leptons'], 0.4)
  candidate_jet:
    field: select_candidate_cjet
    cuts: null
  met:
    field: events.PuppiMET
    cuts: null
  mTll:
    field: select_hww_mTll
    cuts: null
  mTl1:
    field: select_hww_mTl1
    cuts: null
  mTl2: 
    field: select_hww_mTl2
    cuts: null
event_selection:
  selections:
    trigger: get_trigger_mask(events, hlt_paths, dataset_key)
    atleast_one_goodvertex: events.PV.npvsGood > 0
    lumimask: get_lumi_mask(events, goldenjson)
    met_filters: get_metfilters_mask(events, year)
    met_30: objects['met'].pt > 30
    met_45: objects['met'].pt > 45
    one_electron: ak.num(objects['electrons']) == 1
    one_muon: ak.num(objects['muons']) == 1
    atleast_onecjet: ak.num(objects['cjets']) > 0
    atleast_two_cjets: ak.num(objects['cjets']) > 1
    transverse_mass_signal: ak.all((objects["mTl2"] > 30) & (objects["mTll"] > 60), axis=1)
    transverse_mass_top: ak.all((objects["mTl2"] > 30) & (objects["mTll"] <= 60), axis=1)
    dilepton_mass_signal: ak.all((objects['ll_pairs'].l1 + objects['ll_pairs'].l2).mass <= 72, axis=1)
    dilepton_mass_top: ak.all((objects['ll_pairs'].l1 + objects['ll_pairs'].l2).mass > 72, axis=1)
    dilepton_pt: ((objects['ll_pairs'].l1 + objects['ll_pairs'].l2).pt > 30)
  categories:
    base:
      - atleast_one_goodvertex
      - lumimask
      - met_filters
      - trigger
      - met_30
      - one_electron
      - one_muon
    topCR:
      - atleast_one_goodvertex
      - lumimask
      - met_filters
      - trigger
      - met_45
      - one_electron
      - one_muon
      - atleast_onecjet
      - atleast_two_cjets
      - dilepton_mass_top
      - transverse_mass_top
      - dilepton_pt
histogram_config:
  add_syst_axis: true
  add_weight: true
  axes:
    met:
      type: Regular
      bins: 50
      start: 30
      stop: 600
      label: $p_T^{miss}$ [GeV]
      expression: objects['met'].pt
    met_phi:
      type: Regular
      bins: 50
      start: -3.14159
      stop: 3.14159
      label: $\phi(p_T^{miss})$ 
      expression: objects['met'].phi
    met_raw:
      type: Regular
      bins: 50
      start: 30
      stop: 600
      label: Raw $p_T^{miss}$ [GeV]
      expression: objects['met'].pt_raw
    met_phi_raw:
      type: Regular
      bins: 50
      start: -3.14159
      stop: 3.14159
      label: Raw $\phi(p_T^{miss})$ 
      expression: objects['met'].phi_raw
    lepton1_pt:
      type: Regular
      bins: 50
      start: 5
      stop: 500
      label: $p_T^{\ell_1}$ [GeV]
      expression: objects["ll_pairs"].l1.pt
    lepton2_pt:
      type: Regular
      bins: 50
      start: 5
      stop: 500
      label: $p_T^{\ell_2}$ [GeV]
      expression: objects["ll_pairs"].l2.pt
    lepton1_eta:
      type: Regular
      bins: 50
      start: -2.5
      stop: 2.5
      label: $\eta^{\ell_1}$ 
      expression: objects["ll_pairs"].l1.eta
    lepton2_eta:
      type: Regular
      bins: 50
      start: -2.5
      stop: 2.5
      label: $\eta^{\ell_2}$ 
      expression: objects["ll_pairs"].l2.eta
    lepton1_phi:
      type: Regular
      bins: 50
      start: -3.14159
      stop: 3.14159
      label: $\phi^{\ell_1}$ 
      expression: objects["ll_pairs"].l1.eta
    lepton2_phi:
      type: Regular
      bins: 50
      start: -3.14159
      stop: 3.14159
      label: $\phi^{\ell_2}$ 
      expression: objects["ll_pairs"].l2.eta
    mll:
      type: Regular
      bins: 50
      start: 0
      stop: 500
      label: $m_{\ell \ell}$ 
      expression: objects["mll"]
    mtl1:
      type: Regular
      bins: 50
      start: 0
      stop: 500
      label: $m_T^{\ell_1}$ [GeV]
      expression: objects['mTl1']
    mtl2:
      type: Regular
      bins: 50
      start: 0
      stop: 500
      label: $m_T^{\ell_2}$ [GeV]
      expression: objects['mTl2']
    mtll:
      type: Regular
      bins: 50
      start: 0
      stop: 500
      label: $m_T^{\ell \ell}$ [GeV]
      expression: objects['mTll']
    jet_pt:
      type: Regular
      bins: 50
      start: 20
      stop: 800
      label: Candidate c-jet $p_T$ [GeV]
      expression: objects['candidate_cjet'].pt
    jet_eta:
      type: Regular
      bins: 50
      start: -2.4
      stop: 2.4
      label: Candidate c-jet $\eta$
      expression: objects['candidate_cjet'].eta
    jet_phi:
      type: Regular
      bins: 50
      start: -3.14159
      stop: 3.14159
      label: Candidate c-jet $\phi$
      expression: objects['candidate_cjet'].phi
    jet_multiplicity:
      type: IntCategory
      categories:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
        - 12
        - 13
        - 14
        - 15
      label: c-jets multiplicity
      expression: ak.num(objects['cjets'])
    jet_flavour:
      type: IntCategory
      categories:
        - 0
        - 4
        - 5
      label: c-jets HadronFlavour
      expression: objects['cjets'].hadronFlavour
    ptll:
      type: Regular
      bins: 100
      start: 0
      stop: 500
      label: $p_T^{\ell \ell}$ [GeV]
      expression: objects['ptll']
  layout:
    met:
      - met
      - met_phi
      - met_raw
      - met_phi_raw
    lepton_pt:
      - lepton1_pt
      - lepton2_pt
    lepton_eta:
      - lepton1_eta
      - lepton2_eta
    lepton_phi:
      - lepton1_phi
      - lepton2_phi
    transverse_mass:
      - mtl1
      - mtl2
      - mtll
    dilepton_mass:
      - mll
    dilepton_pt:
      - ptll
    candidate_jet:
      - jet_pt
      - jet_eta
      - jet_phi
    jet_multiplicity:
      - jet_multiplicity
    jet_flavour:
      - jet_flavour
